import React, { useState } from 'react';
import { 
  CheckCircle2, 
  Circle, 
  Clock, 
  BookOpen, 
  TrendingUp
} from 'lucide-react';
import type { RoadmapMilestone } from '../../types';

const defaultMilestones: RoadmapMilestone[] = [
  {
    id: 'ms_1',
    title: 'Foundations of Vector Embeddings & pgvector',
    description: 'Learn vector mathematics, OpenAI text-embedding-3-small, and set up pgvector on Supabase PostgreSQL.',
    category: 'AI & Data Layer',
    estimatedHours: 8,
    completed: true,
    resources: ['OpenAI Embeddings Docs', 'Supabase pgvector Guide'],
  },
  {
    id: 'ms_2',
    title: 'FastAPI Microservice & Asynchronous Audio Handling',
    description: 'Build asynchronous endpoints with Whisper API integration for audio processing and JWT verification.',
    category: 'Backend Engineering',
    estimatedHours: 12,
    completed: true,
    resources: ['FastAPI Docs', 'Whisper Python API'],
  },
  {
    id: 'ms_3',
    title: 'Offline PWA Service Worker & IndexedDB Caching',
    description: 'Implement offline audio recording queue in IndexedDB and synchronize upon network reconnection.',
    category: 'Frontend & PWA',
    estimatedHours: 10,
    completed: false,
    resources: ['MDN Background Sync API', 'idb-keyval library'],
  },
  {
    id: 'ms_4',
    title: 'Supabase Realtime Live Doubt Broadcasting',
    description: 'Subscribe to postgres changes on doubts table to stream mentor answers instantly to the student UI.',
    category: 'Real-Time Architecture',
    estimatedHours: 6,
    completed: false,
    resources: ['Supabase Realtime Subscriptions', 'React useSubscription hook'],
  }
];

export const CareerRoadmap: React.FC = () => {
  const [milestones, setMilestones] = useState<RoadmapMilestone[]>(defaultMilestones);
  const careerGoal = 'Fullstack AI & Distributed Systems Engineer';

  const completedCount = milestones.filter((m) => m.completed).length;
  const progressPercent = Math.round((completedCount / milestones.length) * 100);

  const toggleMilestone = (id: string) => {
    setMilestones(
      milestones.map((m) => (m.id === id ? { ...m, completed: !m.completed } : m))
    );
  };

  return (
    <div className="max-w-4xl mx-auto space-y-8">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="inline-flex items-center gap-2 text-xs font-mono text-cyan-400 uppercase tracking-widest mb-1">
            <span>Person 2 & 3 • Career Roadmap</span>
          </div>
          <h1 className="text-3xl font-extrabold text-white">AI-Generated Milestone Roadmap</h1>
          <p className="text-sm text-slate-400 mt-1">
            Interactive skill checklist generated by GPT-4o-mini tailored to your learning trajectory.
          </p>
        </div>

        {/* Goal badge */}
        <div className="glass-card px-4 py-2 rounded-2xl border border-slate-800 flex items-center gap-2">
          <TrendingUp className="w-4 h-4 text-cyan-400" />
          <span className="text-xs font-medium text-slate-300">{careerGoal}</span>
        </div>
      </div>

      {/* Progress Bar Card */}
      <div className="glass-panel p-6 rounded-3xl border border-slate-800 space-y-3">
        <div className="flex items-center justify-between text-sm">
          <span className="font-semibold text-slate-200">Roadmap Progress</span>
          <span className="font-mono text-cyan-400 font-bold">{progressPercent}% Completed</span>
        </div>

        <div className="w-full bg-slate-900 rounded-full h-3 overflow-hidden border border-slate-800">
          <div
            className="bg-gradient-to-r from-indigo-500 via-cyan-400 to-emerald-400 h-full rounded-full transition-all duration-500"
            style={{ width: `${progressPercent}%` }}
          />
        </div>

        <div className="flex justify-between text-xs text-slate-400 pt-1">
          <span>{completedCount} of {milestones.length} milestones finished</span>
          <span>{milestones.reduce((acc, m) => acc + (m.completed ? m.estimatedHours : 0), 0)} / {milestones.reduce((acc, m) => acc + m.estimatedHours, 0)} hours completed</span>
        </div>
      </div>

      {/* Checklist of Milestones */}
      <div className="space-y-4">
        {milestones.map((milestone, idx) => (
          <div
            key={milestone.id}
            onClick={() => toggleMilestone(milestone.id)}
            className={`p-5 rounded-2xl cursor-pointer transition-all border flex items-start gap-4 ${
              milestone.completed
                ? 'bg-slate-900/40 border-slate-800/60 opacity-80'
                : 'glass-panel border-slate-700/80 hover:border-indigo-500/50 shadow-lg'
            }`}
          >
            <button
              aria-label={`Toggle ${milestone.title}`}
              className="mt-0.5 text-cyan-400 hover:scale-110 transition shrink-0"
            >
              {milestone.completed ? (
                <CheckCircle2 className="w-6 h-6 text-emerald-400 fill-emerald-950" />
              ) : (
                <Circle className="w-6 h-6 text-slate-500 hover:text-cyan-400" />
              )}
            </button>

            <div className="space-y-2 flex-1">
              <div className="flex flex-wrap items-center justify-between gap-2">
                <div className="flex items-center gap-2">
                  <span className="text-xs font-mono text-slate-500">Step {idx + 1}</span>
                  <h3 className={`text-base font-bold ${milestone.completed ? 'line-through text-slate-400' : 'text-slate-100'}`}>
                    {milestone.title}
                  </h3>
                </div>
                <span className="text-xs font-mono px-2.5 py-0.5 rounded-full bg-slate-900 text-slate-300 border border-slate-800">
                  {milestone.category}
                </span>
              </div>

              <p className="text-xs text-slate-400 leading-relaxed">{milestone.description}</p>

              <div className="flex flex-wrap items-center gap-4 text-xs text-slate-500 pt-2 border-t border-slate-800/40">
                <div className="flex items-center gap-1">
                  <Clock className="w-3.5 h-3.5" />
                  <span>~{milestone.estimatedHours} Hours</span>
                </div>
                <div className="flex items-center gap-2">
                  <BookOpen className="w-3.5 h-3.5" />
                  <span>Resources:</span>
                  {milestone.resources.map((r) => (
                    <span key={r} className="text-indigo-400 hover:underline">
                      {r}
                    </span>
                  ))}
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
